if (NOT WIN32)
	find_package(PkgConfig)
	if (PKG_CONFIG_FOUND)
		pkg_check_modules(PC_PQXX libpqxx)
		if (PQXX_FOUND)
			if (PQXX_VERSION STRGREATER "7")
				message(STATUS "libpqxx version ${PQXX_VERSION}, requesting c++17")
				set (CMAKE_CXX_STANDARD 17)
			endif()
		endif()
	endif()
else()
	find_path(PQXX_INCLUDE_DIR pqxx/pqxx PATHS)
	mark_as_advanced(PQXX_INCLUDE_DIR)

	find_library(PQXX_LIBRARIES pqxx)
	mark_as_advanced(PQXX_LIBRARIES)

	find_library(PQ_LIBRARY pq)
	mark_as_advanced(PQ_LIBRARY)

	if(PQXX_LIBRARY AND PQ_LIBRARY AND PQXX_INCLUDE_DIR)
		set(PQXX_FOUND ON)
		message(STATUS "Found pqxx: ${PQXX_LIBRARIES}, ${PQ_LIBRARY}, ${PQXX_INCLUDE_DIR}")
		if(PQXX_VERSION STRGREATER "7")
			message(STATUS "libpqxx version ${PQXX_VERSION}, requesting c++17")
			set (CMAKE_CXX_STANDARD 17)
		endif()
	else()
		message(STATUS "Could NOT find pqxx and pq library")
	endif()
endif()